//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.Parsers.EmvsUniqueIdentifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Advice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.Parsers.EmvsUniqueIdentifier.Properties.Advice", typeof(Advice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can verify the authenticity of medicinal packs by scanning the barcode printed on the outer packaging..
        /// </summary>
        public static string Advice_100 {
            get {
                return ResourceManager.GetString("Advice_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can verify the authenticity of medicinal packs by scanning the barcode printed on the outer packaging. You may need to enter data manually into your software for barcodes that contain data formatted according to ISO/IEC 15434 characters..
        /// </summary>
        public static string Advice_105 {
            get {
                return ResourceManager.GetString("Advice_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can verify the authenticity of most medicinal packs by scanning the barcode printed on the outer packaging. You can verify the authenticity of most medicinal packs by scanning the barcode printed on the outer packaging. If you experience problems when scanning barcodes that contain Format 05 or Format 06 data, enter data manually into your software. If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_110 {
            get {
                return ResourceManager.GetString("Advice_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can verify the authenticity of most medicinal packs by scanning the barcode printed on the outer packaging. You can verify the authenticity of most medicinal packs by scanning the barcode printed on the outer packaging. Enter data manually into your software for barcodes that contain Format 05 or Format 06 data. If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_115 {
            get {
                return ResourceManager.GetString("Advice_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to transmit AIM identifiers. If you have problems when transmitting AIM identifiers, revert to the current configuration..
        /// </summary>
        public static string Advice_200 {
            get {
                return ResourceManager.GetString("Advice_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may want to switch off Caps Lock and test again..
        /// </summary>
        public static string Advice_205 {
            get {
                return ResourceManager.GetString("Advice_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configurations and reconfigure them if necessary.;;You may want to switch off Caps Lock and test again..
        /// </summary>
        public static string Advice_206 {
            get {
                return ResourceManager.GetString("Advice_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may want to switch Caps Lock off..
        /// </summary>
        public static string Advice_210 {
            get {
                return ResourceManager.GetString("Advice_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to transmit end-of-line sequences and test again. If you have problems when transmitting end-of-line sequences, revert to the current configuration..
        /// </summary>
        public static string Advice_215 {
            get {
                return ResourceManager.GetString("Advice_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have problems verifying medicine packs, configure your barcode scanner so that it does not transmit a prefix..
        /// </summary>
        public static string Advice_220 {
            get {
                return ResourceManager.GetString("Advice_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have problems verifying medicine packs, configure your barcode scanner so that it does not transmit any suffix..
        /// </summary>
        public static string Advice_225 {
            get {
                return ResourceManager.GetString("Advice_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_230 {
            get {
                return ResourceManager.GetString("Advice_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_231 {
            get {
                return ResourceManager.GetString("Advice_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that your barcode scanner is configured to transmit AIM identifiers..
        /// </summary>
        public static string Advice_232 {
            get {
                return ResourceManager.GetString("Advice_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad and transmit AIM identifiers..
        /// </summary>
        public static string Advice_235 {
            get {
                return ResourceManager.GetString("Advice_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience problems when scanning German PPN barcodes, enter data manually into your verification software.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_240 {
            get {
                return ResourceManager.GetString("Advice_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your verification software to verify PPN unique identifiers.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_241 {
            get {
                return ResourceManager.GetString("Advice_241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your verification software to verify PPN unique identifiers.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_245 {
            get {
                return ResourceManager.GetString("Advice_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you expect to verify PPN barcodes, run the test again, this time including the German PPN compatibility test..
        /// </summary>
        public static string Advice_250 {
            get {
                return ResourceManager.GetString("Advice_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, check the configuration of your barcode scanner. Look for settings that will improve keyboard entry performance..
        /// </summary>
        public static string Advice_255 {
            get {
                return ResourceManager.GetString("Advice_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, check the configuration of your barcode scanner. Look for settings that will improve keyboard entry performance..
        /// </summary>
        public static string Advice_256 {
            get {
                return ResourceManager.GetString("Advice_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan other barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_260 {
            get {
                return ResourceManager.GetString("Advice_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan other barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_261 {
            get {
                return ResourceManager.GetString("Advice_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan other barcodes, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_265 {
            get {
                return ResourceManager.GetString("Advice_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan barcodes that contain EDI data, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_270 {
            get {
                return ResourceManager.GetString("Advice_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan barcodes that contain EDI data, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_271 {
            get {
                return ResourceManager.GetString("Advice_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you scan barcodes that contain EDI data, and experience difficulty, try configuring your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_275 {
            get {
                return ResourceManager.GetString("Advice_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode(s)..
        /// </summary>
        public static string Advice_300 {
            get {
                return ResourceManager.GetString("Advice_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode..
        /// </summary>
        public static string Advice_301 {
            get {
                return ResourceManager.GetString("Advice_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.;;Make sure your keyboard layouts match.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_303 {
            get {
                return ResourceManager.GetString("Advice_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode(s)..
        /// </summary>
        public static string Advice_304 {
            get {
                return ResourceManager.GetString("Advice_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again, making sure you scan the correct barcode.;;If you are asked to scan multiple barcodes, make sure you scan them in the correct order..
        /// </summary>
        public static string Advice_305 {
            get {
                return ResourceManager.GetString("Advice_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again..
        /// </summary>
        public static string Advice_306 {
            get {
                return ResourceManager.GetString("Advice_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your verification software cannot compensate, configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_307 {
            get {
                return ResourceManager.GetString("Advice_307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_308 {
            get {
                return ResourceManager.GetString("Advice_308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your verification software cannot compensate, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_309 {
            get {
                return ResourceManager.GetString("Advice_309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_310 {
            get {
                return ResourceManager.GetString("Advice_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your verification software cannot compensate, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_311 {
            get {
                return ResourceManager.GetString("Advice_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_312 {
            get {
                return ResourceManager.GetString("Advice_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_315 {
            get {
                return ResourceManager.GetString("Advice_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_316 {
            get {
                return ResourceManager.GetString("Advice_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your verification software cannot compensate, configure your barcode scanner to match your computer keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_320 {
            get {
                return ResourceManager.GetString("Advice_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Caps Lock off and test again.;;If you must keep Caps Lock switched on while verifying unique identifiers, you may be able to configure your barcode scanner to compensate..
        /// </summary>
        public static string Advice_325 {
            get {
                return ResourceManager.GetString("Advice_325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Caps Lock off and test again..
        /// </summary>
        public static string Advice_326 {
            get {
                return ResourceManager.GetString("Advice_326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary.;;Switch off Caps Lock and test again..
        /// </summary>
        public static string Advice_327 {
            get {
                return ResourceManager.GetString("Advice_327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary.;;Switch off Caps Lock and test again..
        /// </summary>
        public static string Advice_328 {
            get {
                return ResourceManager.GetString("Advice_328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your scanner, keyboard and computer configuration and reconfigure them if necessary. .
        /// </summary>
        public static string Advice_330 {
            get {
                return ResourceManager.GetString("Advice_330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary..
        /// </summary>
        public static string Advice_331 {
            get {
                return ResourceManager.GetString("Advice_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your barcode scanner, keyboard and computer configuration and reconfigure them if necessary..
        /// </summary>
        public static string Advice_332 {
            get {
                return ResourceManager.GetString("Advice_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If possible, configure your computer to use a different keyboard layout.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_335 {
            get {
                return ResourceManager.GetString("Advice_335", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your verification software to verify PPN unique identifiers.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_350 {
            get {
                return ResourceManager.GetString("Advice_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your verification software to verify PPN unique identifiers.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_351 {
            get {
                return ResourceManager.GetString("Advice_351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data manually into your verification software to verify PPN unique identifiers.;;If necessary, configure your barcode scanner to emulate a numeric keypad..
        /// </summary>
        public static string Advice_355 {
            get {
                return ResourceManager.GetString("Advice_355", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again..
        /// </summary>
        public static string Advice_390 {
            get {
                return ResourceManager.GetString("Advice_390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads unique identifiers reliably..
        /// </summary>
        public static string Condition_100 {
            get {
                return ResourceManager.GetString("Condition_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads unique identifiers reliably..
        /// </summary>
        public static string Condition_105 {
            get {
                return ResourceManager.GetString("Condition_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads unique identifiers reliably..
        /// </summary>
        public static string Condition_110 {
            get {
                return ResourceManager.GetString("Condition_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system reads most unique identifiers reliably..
        /// </summary>
        public static string Condition_115 {
            get {
                return ResourceManager.GetString("Condition_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner does not transmit AIM identifiers..
        /// </summary>
        public static string Condition_200 {
            get {
                return ResourceManager.GetString("Condition_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is on, but the letter casing is reported correctly..
        /// </summary>
        public static string Condition_205 {
            get {
                return ResourceManager.GetString("Condition_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is on, but the letter casing is preserved..
        /// </summary>
        public static string Condition_206 {
            get {
                return ResourceManager.GetString("Condition_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is switched on..
        /// </summary>
        public static string Condition_210 {
            get {
                return ResourceManager.GetString("Condition_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner does not transmit an end-of-line sequence..
        /// </summary>
        public static string Condition_215 {
            get {
                return ResourceManager.GetString("Condition_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner transmits a prefix..
        /// </summary>
        public static string Condition_220 {
            get {
                return ResourceManager.GetString("Condition_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner transmits a suffix..
        /// </summary>
        public static string Condition_225 {
            get {
                return ResourceManager.GetString("Condition_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system may not read AIM identifier characters..
        /// </summary>
        public static string Condition_230 {
            get {
                return ResourceManager.GetString("Condition_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read AIM identifier characters..
        /// </summary>
        public static string Condition_231 {
            get {
                return ResourceManager.GetString("Condition_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may not transmit AIM identifiers..
        /// </summary>
        public static string Condition_232 {
            get {
                return ResourceManager.GetString("Condition_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read AIM identifier characters reliably..
        /// </summary>
        public static string Condition_235 {
            get {
                return ResourceManager.GetString("Condition_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read German PPN barcode characters reliably..
        /// </summary>
        public static string Condition_240 {
            get {
                return ResourceManager.GetString("Condition_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read German PPN barcode characters..
        /// </summary>
        public static string Condition_241 {
            get {
                return ResourceManager.GetString("Condition_241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read German PPN barcode characters..
        /// </summary>
        public static string Condition_245 {
            get {
                return ResourceManager.GetString("Condition_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not test compatibility for German PPN barcodes..
        /// </summary>
        public static string Condition_250 {
            get {
                return ResourceManager.GetString("Condition_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data input performance is slower than expected..
        /// </summary>
        public static string Condition_255 {
            get {
                return ResourceManager.GetString("Condition_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data input performance is very poor..
        /// </summary>
        public static string Condition_256 {
            get {
                return ResourceManager.GetString("Condition_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read additional characters reliably..
        /// </summary>
        public static string Condition_260 {
            get {
                return ResourceManager.GetString("Condition_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read additional characters..
        /// </summary>
        public static string Condition_261 {
            get {
                return ResourceManager.GetString("Condition_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system may not read additional data reliably..
        /// </summary>
        public static string Condition_265 {
            get {
                return ResourceManager.GetString("Condition_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain data for Electronic Data Intechange (EDI).
        /// </summary>
        public static string Condition_270 {
            get {
                return ResourceManager.GetString("Condition_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain data for Electronic Data Intechange (EDI).
        /// </summary>
        public static string Condition_271 {
            get {
                return ResourceManager.GetString("Condition_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read barcodes reliably if they contain data for Electronic Data Intechange (EDI).
        /// </summary>
        public static string Condition_275 {
            get {
                return ResourceManager.GetString("Condition_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test failed..
        /// </summary>
        public static string Condition_300 {
            get {
                return ResourceManager.GetString("Condition_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was reported for the barcode..
        /// </summary>
        public static string Condition_301 {
            get {
                return ResourceManager.GetString("Condition_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data was not reported when you scanned the barcode..
        /// </summary>
        public static string Condition_303 {
            get {
                return ResourceManager.GetString("Condition_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was reported for one or more barcodes..
        /// </summary>
        public static string Condition_304 {
            get {
                return ResourceManager.GetString("Condition_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You scanned a barcode out of sequence..
        /// </summary>
        public static string Condition_305 {
            get {
                return ResourceManager.GetString("Condition_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data was not reported when you scanned one or more barcodes..
        /// </summary>
        public static string Condition_306 {
            get {
                return ResourceManager.GetString("Condition_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner and computer have different keyboard layouts..
        /// </summary>
        public static string Condition_307 {
            get {
                return ResourceManager.GetString("Condition_307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner and computer have different keyboard layouts..
        /// </summary>
        public static string Condition_308 {
            get {
                return ResourceManager.GetString("Condition_308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        public static string Condition_309 {
            get {
                return ResourceManager.GetString("Condition_309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        public static string Condition_310 {
            get {
                return ResourceManager.GetString("Condition_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        public static string Condition_311 {
            get {
                return ResourceManager.GetString("Condition_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        public static string Condition_312 {
            get {
                return ResourceManager.GetString("Condition_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner and computer have different keyboard layouts..
        /// </summary>
        public static string Condition_315 {
            get {
                return ResourceManager.GetString("Condition_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden characters in barcodes are not reported correctly..
        /// </summary>
        public static string Condition_316 {
            get {
                return ResourceManager.GetString("Condition_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read unique identifier characters reliably..
        /// </summary>
        public static string Condition_320 {
            get {
                return ResourceManager.GetString("Condition_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is switched on..
        /// </summary>
        public static string Condition_325 {
            get {
                return ResourceManager.GetString("Condition_325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is switched on..
        /// </summary>
        public static string Condition_326 {
            get {
                return ResourceManager.GetString("Condition_326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to upper case..
        /// </summary>
        public static string Condition_327 {
            get {
                return ResourceManager.GetString("Condition_327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to lower case..
        /// </summary>
        public static string Condition_328 {
            get {
                return ResourceManager.GetString("Condition_328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to simulate Caps Lock..
        /// </summary>
        public static string Condition_330 {
            get {
                return ResourceManager.GetString("Condition_330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to upper case..
        /// </summary>
        public static string Condition_331 {
            get {
                return ResourceManager.GetString("Condition_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may be configured to convert characters to lower case..
        /// </summary>
        public static string Condition_332 {
            get {
                return ResourceManager.GetString("Condition_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your keyboard layout supports {0} characters and cannot read unique identifiers reliably..
        /// </summary>
        public static string Condition_335 {
            get {
                return ResourceManager.GetString("Condition_335", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read PPN barcode characters reliably..
        /// </summary>
        public static string Condition_350 {
            get {
                return ResourceManager.GetString("Condition_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read PPN barcode characters..
        /// </summary>
        public static string Condition_351 {
            get {
                return ResourceManager.GetString("Condition_351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read PPN barcode characters..
        /// </summary>
        public static string Condition_355 {
            get {
                return ResourceManager.GetString("Condition_355", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test failed unexpectedly..
        /// </summary>
        public static string Condition_390 {
            get {
                return ResourceManager.GetString("Condition_390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, you did not test compatibility for German PPN barcodes. Your system may not be able to read German PPN barcodes reliably. .
        /// </summary>
        public static string Description_105 {
            get {
                return ResourceManager.GetString("Description_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, your verification software may not read German PPN barcodes correctly..
        /// </summary>
        public static string Description_110 {
            get {
                return ResourceManager.GetString("Description_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, it cannot read German PPN barcodes reliably..
        /// </summary>
        public static string Description_115 {
            get {
                return ResourceManager.GetString("Description_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your verification software may use them to eliminate unnecessary alerts..
        /// </summary>
        public static string Description_200 {
            get {
                return ResourceManager.GetString("Description_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner is probably configured to compensate automatically for Caps Lock or to enter data using the numeric keypad (ALT mode)..
        /// </summary>
        public static string Description_205 {
            get {
                return ResourceManager.GetString("Description_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Caps Lock key may be disabled or remapped. .
        /// </summary>
        public static string Description_206 {
            get {
                return ResourceManager.GetString("Description_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, your computer keyboard layout is for a script that does not support upper- and lower-case letters..
        /// </summary>
        public static string Description_210 {
            get {
                return ResourceManager.GetString("Description_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may slow your scanning performance. However, your verification software may not support end-of-line sequences..
        /// </summary>
        public static string Description_215 {
            get {
                return ResourceManager.GetString("Description_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification software may not recognise the prefix. .
        /// </summary>
        public static string Description_220 {
            get {
                return ResourceManager.GetString("Description_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification software may not recognise the suffix. .
        /// </summary>
        public static string Description_225 {
            get {
                return ResourceManager.GetString("Description_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your verification software may use them to eliminate unnecessary alerts. However, the software must implement character mapping to read AIM identifiers reliably..
        /// </summary>
        public static string Description_230 {
            get {
                return ResourceManager.GetString("Description_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your verification software may use them to eliminate unnecessary alerts..
        /// </summary>
        public static string Description_231 {
            get {
                return ResourceManager.GetString("Description_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner may transmit AIM identifiers, but this is not certain.  AIM identifiers represent the barcode type. Your verification software may use them to eliminate unnecessary alerts..
        /// </summary>
        public static string Description_232 {
            get {
                return ResourceManager.GetString("Description_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM identifiers represent the barcode type. Your verification software may use them to eliminate unnecessary alerts..
        /// </summary>
        public static string Description_235 {
            get {
                return ResourceManager.GetString("Description_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software must implement character mapping to read PPN barcodes reliably..
        /// </summary>
        public static string Description_240 {
            get {
                return ResourceManager.GetString("Description_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some verification software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        public static string Description_245 {
            get {
                return ResourceManager.GetString("Description_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could be a temporary or intermittent problem. Your computer may be busy, running a virus checker or a predictive text service. Your barcode scanner may be configured as a numeric keypad..
        /// </summary>
        public static string Description_255 {
            get {
                return ResourceManager.GetString("Description_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could be a temporary or intermittent problem. Your computer may be busy, running a virus checker or a predictive text service. Your barcode scanner may be configured as a numeric keypad..
        /// </summary>
        public static string Description_256 {
            get {
                return ResourceManager.GetString("Description_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain additional characters that never appear in unique identifiers. Your software must implement character mapping to read these barcodes reliably..
        /// </summary>
        public static string Description_260 {
            get {
                return ResourceManager.GetString("Description_260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain additional characters that never appear in unique identifiers..
        /// </summary>
        public static string Description_261 {
            get {
                return ResourceManager.GetString("Description_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain additional characters that never appear in unique identifiers..
        /// </summary>
        public static string Description_265 {
            get {
                return ResourceManager.GetString("Description_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain EDI data. Your software must implement character mapping to read these barcodes reliably..
        /// </summary>
        public static string Description_270 {
            get {
                return ResourceManager.GetString("Description_270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain EDI data..
        /// </summary>
        public static string Description_271 {
            get {
                return ResourceManager.GetString("Description_271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some barcodes may contain EDI data..
        /// </summary>
        public static string Description_275 {
            get {
                return ResourceManager.GetString("Description_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have scanned a wrong barcode or entered incorrect data using the keyboard. Your barcode scanner or system may be slow, or some unexpected or intermittent issue may have occurred..
        /// </summary>
        public static string Description_300 {
            get {
                return ResourceManager.GetString("Description_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode scanner and computer keyboard layouts may not correspond. You may have scanned a wrong barcode or entered incorrect data using the keyboard. Your barcode scanner or system may be slow, or some unexpected or intermittent issue may have occurred..
        /// </summary>
        public static string Description_303 {
            get {
                return ResourceManager.GetString("Description_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have scanned a wrong barcode or entered incorrect data using the keyboard. Your barcode scanner or system may be slow, or some unexpected or intermittent issue may have occurred..
        /// </summary>
        public static string Description_306 {
            get {
                return ResourceManager.GetString("Description_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification software must implement character mapping to read unique identifiers reliably..
        /// </summary>
        public static string Description_307 {
            get {
                return ResourceManager.GetString("Description_307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification software may be able to compensate..
        /// </summary>
        public static string Description_309 {
            get {
                return ResourceManager.GetString("Description_309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification software may be able to compensate..
        /// </summary>
        public static string Description_311 {
            get {
                return ResourceManager.GetString("Description_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification software may be able to compensate. However, your system cannot read German PPN barcode characters correctly. Some verification software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        public static string Description_315 {
            get {
                return ResourceManager.GetString("Description_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification software may be able to compensate. However, your system cannot read German PPN barcode characters correctly. Some verification software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        public static string Description_316 {
            get {
                return ResourceManager.GetString("Description_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some verification software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        public static string Description_320 {
            get {
                return ResourceManager.GetString("Description_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Caps Lock is on, the default behaviour is to report all characters in upper-case..
        /// </summary>
        public static string Description_326 {
            get {
                return ResourceManager.GetString("Description_326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read unique identifier characters reliably..
        /// </summary>
        public static string Description_327 {
            get {
                return ResourceManager.GetString("Description_327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read unique identifier characters reliably..
        /// </summary>
        public static string Description_328 {
            get {
                return ResourceManager.GetString("Description_328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read unique identifier characters reliably..
        /// </summary>
        public static string Description_331 {
            get {
                return ResourceManager.GetString("Description_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system cannot read unique identifier characters reliably..
        /// </summary>
        public static string Description_332 {
            get {
                return ResourceManager.GetString("Description_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software must implement character mapping to read PPN barcodes reliably..
        /// </summary>
        public static string Description_350 {
            get {
                return ResourceManager.GetString("Description_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some verification software may be able to compensate for this by analysing key codes rather than characters..
        /// </summary>
        public static string Description_355 {
            get {
                return ResourceManager.GetString("Description_355", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your barcode scanner or system may be slow or it may be affected by anti-virus software or some other unexpected or intermittent issue..
        /// </summary>
        public static string Description_390 {
            get {
                return ResourceManager.GetString("Description_390", resourceCulture);
            }
        }
    }
}
