//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.Parsers.EmvsUniqueIdentifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.Parsers.EmvsUniqueIdentifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid advice item..
        /// </summary>
        internal static string CalibrationInvalidAdviceItem {
            get {
                return ResourceManager.GetString("CalibrationInvalidAdviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode does not contain a{0} product code..
        /// </summary>
        internal static string Packs_Error_001 {
            get {
                return ResourceManager.GetString("Packs_Error_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode does not contain a{0} batch identifier..
        /// </summary>
        internal static string Packs_Error_002 {
            get {
                return ResourceManager.GetString("Packs_Error_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode does not contain a{0} expiry date..
        /// </summary>
        internal static string Packs_Error_003 {
            get {
                return ResourceManager.GetString("Packs_Error_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode does not contain a{0} serial number..
        /// </summary>
        internal static string Packs_Error_004 {
            get {
                return ResourceManager.GetString("Packs_Error_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided..
        /// </summary>
        internal static string Parser_Error_001 {
            get {
                return ResourceManager.GetString("Parser_Error_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode symbology is not supported for pack identifiers..
        /// </summary>
        internal static string Parser_Error_002 {
            get {
                return ResourceManager.GetString("Parser_Error_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The barcode does not contain a unique pack identifier..
        /// </summary>
        internal static string Parser_Error_003 {
            get {
                return ResourceManager.GetString("Parser_Error_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pack identifier contains invalid or unrecognised data..
        /// </summary>
        internal static string Parser_Error_004 {
            get {
                return ResourceManager.GetString("Parser_Error_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pack identifier contains multiple national numbers for {0}..
        /// </summary>
        internal static string Parser_Error_005 {
            get {
                return ResourceManager.GetString("Parser_Error_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product code..
        /// </summary>
        internal static string Parser_Error_006 {
            get {
                return ResourceManager.GetString("Parser_Error_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product code is invalid..
        /// </summary>
        internal static string Parser_Error_007 {
            get {
                return ResourceManager.GetString("Parser_Error_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be 14 characters in length..
        /// </summary>
        internal static string Parser_Error_008 {
            get {
                return ResourceManager.GetString("Parser_Error_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value contains non-digit characters..
        /// </summary>
        internal static string Parser_Error_009 {
            get {
                return ResourceManager.GetString("Parser_Error_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checksum value is incorrect..
        /// </summary>
        internal static string Parser_Error_010 {
            get {
                return ResourceManager.GetString("Parser_Error_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be 12 characters in length..
        /// </summary>
        internal static string Parser_Error_011 {
            get {
                return ResourceManager.GetString("Parser_Error_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PPN PRAC (Product Registration Agency Code) is invalid..
        /// </summary>
        internal static string Parser_Error_012 {
            get {
                return ResourceManager.GetString("Parser_Error_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PZN checksum is invalid, and therefore the PPN is invalid..
        /// </summary>
        internal static string Parser_Error_013 {
            get {
                return ResourceManager.GetString("Parser_Error_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No batch identifier (lot)..
        /// </summary>
        internal static string Parser_Error_014 {
            get {
                return ResourceManager.GetString("Parser_Error_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch identifier is invalid..
        /// </summary>
        internal static string Parser_Error_015 {
            get {
                return ResourceManager.GetString("Parser_Error_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 1 and 20 characters in length..
        /// </summary>
        internal static string Parser_Error_016 {
            get {
                return ResourceManager.GetString("Parser_Error_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value contains disallowed characters..
        /// </summary>
        internal static string Parser_Error_017 {
            get {
                return ResourceManager.GetString("Parser_Error_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expiry date provided..
        /// </summary>
        internal static string Parser_Error_018 {
            get {
                return ResourceManager.GetString("Parser_Error_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expiry date is invalid..
        /// </summary>
        internal static string Parser_Error_019 {
            get {
                return ResourceManager.GetString("Parser_Error_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No serial number provided..
        /// </summary>
        internal static string Parser_Error_020 {
            get {
                return ResourceManager.GetString("Parser_Error_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serial number is invalid..
        /// </summary>
        internal static string Parser_Error_021 {
            get {
                return ResourceManager.GetString("Parser_Error_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character {0} does not represent a digit..
        /// </summary>
        internal static string Parser_Error_100 {
            get {
                return ResourceManager.GetString("Parser_Error_100", resourceCulture);
            }
        }
    }
}
