//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.EmvsUniqueIdentifierTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.EmvsUniqueIdentifierTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibrationView - do not call Render.
        /// </summary>
        internal static string CalibrationViewDoNotCallRender {
            get {
                return ResourceManager.GetString("CalibrationViewDoNotCallRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Clear console buffer ----.
        /// </summary>
        internal static string ClearConsoleBuffer {
            get {
                return ResourceManager.GetString("ClearConsoleBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialise code page {0}.
        /// </summary>
        internal static string CodePageInitialiseError {
            get {
                return ResourceManager.GetString("CodePageInitialiseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue, using default code page....
        /// </summary>
        internal static string CodePageInitialiseErrorRecovery {
            get {
                return ResourceManager.GetString("CodePageInitialiseErrorRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePage = {0}.
        /// </summary>
        internal static string CodePageInitialiseFakeCommandLine {
            get {
                return ResourceManager.GetString("CodePageInitialiseFakeCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan barcode&gt;.
        /// </summary>
        internal static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMVS Unique Identifier Tester.
        /// </summary>
        internal static string ConsoleTitle {
            get {
                return ResourceManager.GetString("ConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVICE.
        /// </summary>
        internal static string DisplayAdvice_1 {
            get {
                return ResourceManager.GetString("DisplayAdvice_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current combination of barcode and Operating System keyboard layouts cannot be calibrated..
        /// </summary>
        internal static string DisplayCalibrationFailedMessage_1 {
            get {
                return ResourceManager.GetString("DisplayCalibrationFailedMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that you have scanned the correct barcode for calibration. If you have, reconfigure the.
        /// </summary>
        internal static string DisplayCalibrationFailedMessage_2 {
            get {
                return ResourceManager.GetString("DisplayCalibrationFailedMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scanner to emulate a different keyboard layout or a numeric keypad..
        /// </summary>
        internal static string DisplayCalibrationFailedMessage_3 {
            get {
                return ResourceManager.GetString("DisplayCalibrationFailedMessage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string DisplayCalibrationInformation_1 {
            get {
                return ResourceManager.GetString("DisplayCalibrationInformation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Scan the barcode to calibrate the tester application..
        /// </summary>
        internal static string DisplayCalibrationOptions_1 {
            get {
                return ResourceManager.GetString("DisplayCalibrationOptions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Press Ctrl-O to exit the calibration mode..
        /// </summary>
        internal static string DisplayCalibrationOptions_2 {
            get {
                return ResourceManager.GetString("DisplayCalibrationOptions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALIBRATION REPORT.
        /// </summary>
        internal static string DisplayCalibrationReport_1 {
            get {
                return ResourceManager.GetString("DisplayCalibrationReport_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string DisplayCalibrationSaveError_1 {
            get {
                return ResourceManager.GetString("DisplayCalibrationSaveError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep scanning....
        /// </summary>
        internal static string DisplayKeepScanning_1 {
            get {
                return ResourceManager.GetString("DisplayKeepScanning_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Scan a barcode..
        /// </summary>
        internal static string DisplayMainOptions_1 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Type in or paste data and press Enter..
        /// </summary>
        internal static string DisplayMainOptions_2 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Press Ctrl-R to toggle between automatic and manual (carriage return) submission of data..
        /// </summary>
        internal static string DisplayMainOptions_3 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Press Ctrl-K to calibrate the tester for the current scanner and keyboard layout..
        /// </summary>
        internal static string DisplayMainOptions_4 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Press Shift Ctrl-K to calibrate the tester for the current scanner and keyboard layout for GS1 FNC barcodes, only..
        /// </summary>
        internal static string DisplayMainOptions_5 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Press Ctrl-S to clear the screen..
        /// </summary>
        internal static string DisplayMainOptions_6 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Press Ctrl-T to exit the program..
        /// </summary>
        internal static string DisplayMainOptions_7 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Press Up and Down Arrows to select and retry cached entries..
        /// </summary>
        internal static string DisplayMainOptions_8 {
            get {
                return ResourceManager.GetString("DisplayMainOptions_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input contains one or more characters that cannot be encoded..
        /// </summary>
        internal static string DisplayParserResults_1 {
            get {
                return ResourceManager.GetString("DisplayParserResults_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARSER ERROR:.
        /// </summary>
        internal static string DisplayParserResults_2 {
            get {
                return ResourceManager.GetString("DisplayParserResults_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        internal static string DisplayParserResults_3 {
            get {
                return ResourceManager.GetString("DisplayParserResults_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string Initialise_1 {
            get {
                return ResourceManager.GetString("Initialise_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  □ represents an invalid character .
        /// </summary>
        internal static string InvalidCharacterPlaceHolderMessage {
            get {
                return ResourceManager.GetString("InvalidCharacterPlaceHolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCHandle Target could not be cast as List&lt;IntPtr&gt;.
        /// </summary>
        internal static string ListIntPtrCastError {
            get {
                return ResourceManager.GetString("ListIntPtrCastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application requires VT sequences which are not supported on this platform..
        /// </summary>
        internal static string VtSequencesNotSupported {
            get {
                return ResourceManager.GetString("VtSequencesNotSupported", resourceCulture);
            }
        }
    }
}
